/**
 * ============================================================
 *  MUSIC: page wording and every release, in one place.
 * ============================================================
 *  Add a song by adding an entry to `releases`. The pages update
 *  themselves based on `status` and on which fields are filled in:
 *
 *    COMING_SOON  → "Coming Soon" card, no player, no listen buttons
 *    UNRELEASED   → "Unreleased" card; shows a preview player only if `audioPreview` is set
 *    RELEASED     → "Listen Now" + a button for every streaming link that is filled in
 *
 *  Leave anything you don't have as null. Never add placeholder titles,
 *  dates or links: an empty field is simply hidden.
 *
 *  Files:
 *    Artwork  → public/images/music/<file>.jpg   then  cover: { src: "/images/music/<file>.jpg", … }
 *    Audio    → public/music/<file>.mp3          then  audioPreview: { src: "/music/<file>.mp3" }
 *    ⚠ Anything in /public can be downloaded by anyone who has the link.
 *      Only put audio there that you're happy to share publicly. See
 *      src/content/MUSIC.md for how private/unreleased audio would be handled.
 */
import type { MusicRelease } from "./types";

export const musicPage = {
  heading: "Music",
  intro: "Beyond the written word, Abimbola also expresses her faith through music.",
  /** A short, understated paragraph under the intro. */
  body: "Music is another way of telling the same story: faith, reflection and hope, carried in melody instead of on the page.",

  /** Shown when nothing has been released yet. */
  comingSoon: {
    heading: "New Music Coming Soon",
    text: "Something special is on the way.",
  },

  /** Homepage teaser. */
  teaser: {
    eyebrow: "Music",
    heading: "Also, Through Music…",
    text: "Abimbola also expresses her faith through music.",
    emptyNote: "New music coming soon.",
    cta: "Explore Music",
  },

  /** Shown under upcoming songs (no platform is named until its link exists). */
  streamingNote: "These songs are coming soon to streaming platforms. Listening links will appear here as each one is released.",

  /** /music/upcoming */
  upcoming: {
    heading: "Upcoming Music",
    intro: "New music is on the way. Upcoming and unreleased projects will appear here.",
  },
};

export const releases: MusicRelease[] = [
  /*
   * Upcoming releases. Each is UNRELEASED: finished, not yet on streaming
   * platforms. When a song comes out, set status: "RELEASED", add its
   * releaseDate and streaming links, and it gets "Listen Now" automatically.
   * Previews are short snippets only (never the full song).
   */
  {
    slug: "the-battle-has-been-won",
    visible: true,
    status: "UNRELEASED",
    title: "The Battle Has Been Won",
    artist: "Abimbola Olumuyiwa",
    // Artwork generated by scripts/generate-music-covers.mjs (replace with official art any time).
    cover: { src: "/images/music/the-battle-has-been-won.jpg", alt: "Artwork for The Battle Has Been Won: sunrise rays breaking over quiet hills in warm browns and gold", width: 1400, height: 1400 },
    description: null,
    releaseDate: null,
    // 20-second snippet (4:13–4:33 of the song), faded in and out.
    audioPreview: { src: "/music/the-battle-has-been-won-preview.m4a", type: "audio/mp4" },
    lyricsUrl: null,
    youtubeUrl: null,
    spotifyUrl: null,
    appleMusicUrl: null,
    otherLinks: [],
  },
  {
    slug: "tremble",
    visible: true,
    status: "UNRELEASED",
    title: "Tremble",
    artist: "Abimbola Olumuyiwa",
    // Artwork generated by scripts/generate-music-covers.mjs (replace with official art any time).
    cover: { src: "/images/music/tremble.jpg", alt: "Artwork for Tremble: rippling rings radiating from a point of light on deep sage green", width: 1400, height: 1400 },
    description: null,
    releaseDate: null,
    audioPreview: null, // add a snippet file to show a preview player
    lyricsUrl: null,
    youtubeUrl: null,
    spotifyUrl: null,
    appleMusicUrl: null,
    otherLinks: [],
  },
  {
    slug: "oh-king-of-kings",
    visible: true,
    status: "UNRELEASED",
    title: "Oh King of Kings",
    artist: "Abimbola Olumuyiwa",
    // Artwork generated by scripts/generate-music-covers.mjs (replace with official art any time).
    cover: { src: "/images/music/oh-king-of-kings.jpg", alt: "Artwork for Oh King of Kings: a fine golden crown beneath a scatter of stars on dark brown", width: 1400, height: 1400 },
    description: null,
    releaseDate: null,
    audioPreview: null,
    lyricsUrl: null,
    youtubeUrl: null,
    spotifyUrl: null,
    appleMusicUrl: null,
    otherLinks: [],
  },

  // Example of a released song (copy, fill in, and remove the // marks):
  // {
  //   slug: "song-title",
  //   visible: true,
  //   status: "RELEASED",
  //   title: "Song Title",
  //   artist: "Abimbola Olumuyiwa",
  //   cover: { src: "/images/music/song-title.jpg", alt: "Artwork for Song Title", width: 1400, height: 1400 },
  //   description: "A sentence about the song.",
  //   releaseDate: "2026-12-01",
  //   audioPreview: { src: "/music/song-title-preview.mp3", type: "audio/mpeg" },
  //   lyricsUrl: null,
  //   youtubeUrl: "https://www.youtube.com/watch?v=…",
  //   spotifyUrl: "https://open.spotify.com/track/…",
  //   appleMusicUrl: "https://music.apple.com/…",
  //   otherLinks: [],
  // },
];
